fetch('https://jsonplaceholder.typicode.com/photos')
.then((res)=>{
    res.json()
    .then((response)=>{
        console.log(response);
    })
    .catch((error)=>{
        console.log(error);
    })
})
.catch((err)=>{
    console.log(err);
})